### ISSUE TITLE
Thanks for this

### ISSUE THREAD

**Issue by ScriptedAlchemy** [mmmeff/content-hashed-module-ids-webpack-plugin#1]
Did a google search. And found this repo. 

First glance (on my phone) it looks like this will work really well with a project I’m working on. https://github.com/ScriptedAlchemy/webpack-external-import

Basically interleaving modules between bundles so multiple webpack builds act as one. 

Really appreciate your efforts on this. It’s going to be a massive help. 

Have you run into any issues or risks by mutating module ids? I’m mutating some module ids, however when it comes to dependency chains, your implementation is going to be a huge unlock for me 

Thanks again! Let me know if you need any help

**Comment by mmmeff** [comment]
Thanks Zack! I followed up via e-mail. Resolving.
